version: "3.3"
services:

  neural:
    image: lifefilm/fastai2_fastapi_cpu:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    volumes:
      - .:/app
      - /tmp:/tmp
      - ./predicted:/app/predicted
    ports:
      - 8001:8001
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    networks:
      - default
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001

